#!/bin/bash
s_shelp()
{
    cat <<EOF
This command add a permission of a certain action to polkit
USAGE:
	$0 [OPTIONS] policies
OPTIONS:
	-u/--user USER: to add a permission for USER
	-v/--version: show the version number
	-h/--help: show this help and exit
EOF
}

. s_init.sh

if [ $(id -u) != "0" ] ;then
    sudo $0 -u $(whoami) $@
    exit
fi

for ((i = 0;i <= $#;)) ;do
    case ${!i} in
	-u|--user)
	    shift $i
	    S_USERNAME=${!i}
	    shift $i
	    ;;
	*)
	    let 'i++'
	    ;;
	esac
done

for arg in $@
do
    cat <<EOF
[${arg}]
Identity=unix-user:${S_USERNAME}
Action=${arg}
ResultAny=no
ResultInactive=no
ResultActive=yes
EOF 
>> /etc/polkit-1/localauthority/50-local.d/${arg}.pkla
done
