#!/bin/bash -e

. s_init.sh

action=0

for ((i = 0;i < ${#args[@]};)) ;do
    case "$args[i]" in
        -n)
            [[ $action == 2 ]] && {
                echo "Only one action can be done." >&2
                exit 1
            }
            action=1
            dargs $i
            ;;
        -u)
            [[ $action == 1 ]] && {
                echo "Only one action can be done." >&2
                exit 1
            }
            action=2
            dargs $i
            ;;
        *)
            let 'i++' || true
            ;;
    esac
done

nroot="${args[0]}"

[[ $nroot == '' ]] && {
    echo "Need a path to chroot to."
    exit 1
}
[[ $nroot =~ ^/*$ ]] && {
    echo "Cannot change root to current root."
    exit 1
}
mkdir -p "$nroot"
[[ ! -d $nroot ]] && {
    echo "${nroot} doesn't exist"
    exit 1
}
sub_dirs=(dev proc sys dev/pts dev/shm)
if [[ $action == 0 ]] || [[ $action == 1 ]] ;then
    for ((i = 0;i < ${#sub_dirs[@]};i++)) ;do
        mkdir -p ${nroot}/${sub_dirs[i]} &&
        mount --bind /"${sub_dirs[i]}" "${nroot}/${sub_dirs[i]}" || break
    done
fi
result=0
case $action in
    0)
        (( i >= ${#sub_dirs[@]} )) && {
            chroot "${nroot}"
            ((i--))
        }
        ;;
    1)
        (( i >= ${#sub_dirs[@]} )) && exit 0
        result=1
        ;;
esac
for ((;i >= 0;i--)) ;do
    umount "${nroot}/${sub_dirs[i]}"
done
exit ${result}
