#!/bin/bash -e

. s_init.sh

for ((i = 0;i < ${#args[@]};i++)) ;do
    case "$args[i]" in
	-n)
	    nochroot=1
	    dargs $i
	    ;;
	-u)
	    unbind=1
	    dargs $i
	    ;;
    esac
done

nroot="${args[0]}"

[[ $nroot == '' ]] && {
    echo "Need a path to chroot to."
    exit 1
}
[[ $nroot =~ ^/*$ ]] && {
    echo "Cannot change root to current root."
    exit 1
}
[[ ! -d $nroot ]] && {
    echo "${nroot} doesn't exist"
    exit 1
}
sub_dirs=(dev proc sys dev/pts dev/shm)
for ((i = 0;i < ${#sub_dirs[@]};i++)) ;do
    mkdir -p ${nroot}/${sub_dirs[i]} &&
    mount --bind /"${sub_dirs[i]}" "${nroot}/${sub_dirs[i]}" || break
done
if [[ $nochroot ]] ;then
    (( i >= ${#sub_dirs[@]} )) && exit 0
else
    chroot "${nroot}"
    ((i--))
fi
for ((;i >= 0;i--)) ;do
    umount "${nroot}/${sub_dirs[i]}"
done
