#!/bin/bash

. s_init.sh

nroot="${args[0]}"

[[ $nroot == '' ]] && {
    echo "Need a path to chroot to."
    exit 1
}
[[ $nroot =~ ^/*$ ]] && {
    echo "Cannot change root to current root."
    exit 1
}
[[ ! -d $nroot ]] && {
    echo "${nroot} doesn't exist"
    exit 1
}
sub_dirs=(dev proc sys dev/pts dev/shm)
for ((i = 0;i < ${#sub_dirs[@]};i++)) ;do
    mkdir -p ${dir}/${sub_dirs[i]} ||
    exit 1
done
for ((i = 0;i < ${#sub_dirs[@]};i++)) ;do
    mount --bind /"${sub_dirs[i]}" "${dir}/${subdirs[i]}" || break
done
(( i >= ${#sub_dirs[@]} )) && exit 0
for ((;i >= 0;i--)) ;do
    umount "${dir}/${sub_dirs[i]}"
done
