#!/bin/bash
HELP_INFO='This script clean up all the backup files (*~) in current directory.'
. s_init.sh

rec=0

for ((i = 1;i <= $#;i++)) ;do
    case ${!i} in
	-r)
	    rec=1
	    ;;
    esac
done

if [ $rec = 1 ] ;then
    find -name "*~" -exec rm {} /;
else
    find -name "*~" -maxdepth 1 -exec rm {} /;
fi
