#!/bin/bash

# Copyright 2010, 2011 Yu Yichao, Rudy
# yyc1992@gmail.com
# rudyht@gmail.com
#
# This file is part of s-util.
#
# s-util is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# s-util is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with s-util.  If not, see <http://www.gnu.org/licenses/>.
#

HELP_INFO='This script clean up all the backup files (*~) in current directory.'
. s_init.sh

rec=0

for ((i = 0;i < ${#args[@]};i++)) ;do
    case "${args[i]}" in
        -r)
            rec=1
            ;;
    esac
done

if [ "$rec" = 1 ] ;then
    find -name "*~" -exec rm {} \;
else
    find -maxdepth 1 -name "*~" -exec rm {} \;
fi
