#!/bin/bash
HELP_INFO='This script delete all the empty folders recursively.'

. "${S_UTIL_INSTALL_DIR}/s_init.sh"

[ "$#" = "0" ] && find -depth -type d -exec rmdir {} \; 2> /dev/null

for ((i = 1;i <= $#;i++)) ;do
    [ -z "${!i}" ] && continue
    if [ -d "${!i}" ] ;then
	path="${!i}"
    elif [ -f "${!i}" ] ;then
	path="${!i%/*}"
	if [ -z "$path" ] ;then
	    path=.
	fi
    else
	continue
    fi
    [ -z "$path" -o ! -d "$path" ] && continue
    find "${path}" -depth -type d -exec rmdir {} \; 2> /dev/null
done
