#!/bin/bash

# Copyright 2010, 2011 Yu Yichao, Rudy
# yyc1992@gmail.com
# rudyht@gmail.com
#
# This file is part of s-util.
#
# s-util is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# s-util is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with s-util.  If not, see <http://www.gnu.org/licenses/>.
#

HELP_INFO='This script delete all the empty folders recursively.'

. s_init.sh

[[ "${#args[@]}" == 0 ]] && find -depth -type d -exec rmdir {} \; 2> /dev/null

for ((i = 0;i < ${#args[@]};i++)) ;do
    [ -z "${args[i]}" ] && continue
    if [ -d "${args[i]}" ] ;then
        path="${args[i]}"
    elif [ -f "${args[i]}" ] ;then
        path="${args[i]%/*}"
        if [ -z "$path" ] ;then
            path=.
        fi
    else
        continue
    fi
    [ -z "$path" -o ! -d "$path" ] && continue
    find "$path" -depth -type d -exec rmdir {} \; 2> /dev/null
done
