#!/bin/bash
s_shelp()
{
    cat <<EOF
This is a command line clipboard
USAGE
	$(basename ${0}) [OPTIONS] FILENAMES
OPTIONS
	-d: delete from clipboard
	-p: paste from clipboard
	-c: copy files from current dir
	-v/--version: show the version number and exit
	-h/--help: show this help and exit
EOF
}

. s_init.sh

__rname()
{
    type logname &> /dev/null && {
	logname 2> /dev/null ||
	whoami
    }
}

eval clpdir=~$(logname)/.sutil/_s_clipboard

[ -d "${clpdir}" ] || mkdir -p "${clpdir}" || exit 1

LN="ln"
CP="cp -i"
RM="rm"

__copy()
{
    for ((i = 1;i <= $#;i++)) ;do
	if [[ "${!i}" =~ ^/ ]] ;then
	    file="${!i}"
	else
	    file="${PWD}/${!i}"
	fi
	${LN} -s "${file}" "${clpdir}" || exit 1
    done
}

__paste()
{
    for ((i = 1;i <= $#;i++)) ;do
	file="${clpdir}/${!i}"
	if [ -d "${file}" ] ;then
	    ${CP} -r "${file}/" . || exit 1
	else
	    if [ -f "${file}" ] ;then
		${CP} "${file}" . || exit 1
	    else
		exit 1
	    fi
	fi
    done
}

__delete()
{
    for ((i = 1;i <= $#;i++)) ;do
	file="$(echo "${clpdir}/${!i}" | sed -e 's:/*$::g')"
	${RM} "$file" || exit 1
    done
}

case "${args[0]}" in
    -c|--copy)
	darg
	__copy "${args[@]}"
	;;
    -p|--paste)
	darg
	__paste "${args[@]}"
	;;
    -d|--delete)
	darg
	__delete "${args[@]}"
	;;
    *)
	echo "Unrecognized option ${args[0]}"
	exit 1
	;;
esac
exit 0