#!/bin/bash
if [[ "$BASH_SOURCE" =~ ^/ ]] ;then
    dst="$(dirname "${BASH_SOURCE}")/_pb"
else
    dst="${PWD}/$(dirname "${BASH_SOURCE}")/_pb"
fi

for ((i = 1;i <= $#;i++)) ;do
    if [[ "${!i}" =~ ^/ ]] ;then
	file="${!i}"
    else
	file="${PWD}/${!i}"
    fi
    ln -s "${file}" "${dst}"
done