#!/bin/bash

# Copyright 2010, 2011 Yu Yichao, Rudy
# yyc1992@gmail.com
# rudyht@gmail.com
#
# This file is part of s-util.
#
# s-util is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# s-util is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with s-util.  If not, see <http://www.gnu.org/licenses/>.
#

chs_edtr()
{
    local edtrlst=('vim' 'emacs' 'vi' 'nano') edtr
    [[ ${EDITOR} != "" ]] && {
        echo $EDITOR
        return 0
    }
    type editor &> /dev/null && {
        echo editor
        return 0
    }
    [[ -z $DISPLAY ]] || {
        type xdg-open &> /dev/null && {
            echo xdg-open
            return 0
        }
    }
    for edtr in ${edtolst[@]} ;do
        type "${edtr}" &> /dev/null && {
            echo ${edtr}
            return 0
        }
    done
    echo "Cannot find a editor to use. Please set EDITOR or link editor to the editor you want to use." >&2
    return 1
}

filelist=$(find -name "*.h" -o -name "*.c" -o -name "*.cpp" -o -iname "makefile" -o -name "*.py" -o -name "*.rb" -o -name "*.js" -o -name "*.ui")
[[ -z $filelist ]] && {
    echo "No file found" >&2
    exit 1
}
edtr="$(chs_edtr)" || exit $?
if [[ -z $DISPLAY ]] ;then
    ${edtr} ${filelist}
else
    ${edtr} ${filelist} &> /dev/null &    
fi
