#!/bin/bash
dst=/tmp/_s_clipboard

[ -d /tmp/_s_clipboard ] || mkdir -m777 /tmp/_s_clipboard

for ((i = 1;i <= $#;i++)) ;do
    if [[ "${!i}" =~ ^/ ]] ;then
	file="${!i}"
    else
	file="${PWD}/${!i}"
    fi
    ln -s "${file}" "${dst}"
done