#!/bin/bash
srcdir=/tmp/_s_clipboard

for ((i = 1;i <= $#;i++)) ;do
    file="${srcdir}/${!i}"
    if [ -d "${file}" ] ;then
	cp -r "${file}/" .
    else
	if [ -f "${file}" ] ;then
	    cp "${file}" .
	fi
    fi
done
