#!/bin/bash
if [[ "$BASH_SOURCE" =~ ^/ ]] ;then
    srcdir="$(dirname "${BASH_SOURCE}")/_pb"
else
    srcdir="${PWD}/$(dirname "${BASH_SOURCE}")/_pb"
fi

for ((i = 1;i <= $#;i++)) ;do
    file="${srcdir}/${!i}"
    if [ -d "${file}" ] ;then
	cp -r "${file}/" .
    else
	if [ -f "${file}" ] ;then
	    cp "${file}" .
	fi
    fi
done
