#!/bin/bash
s_uninstall()
{
    [ -r s_u_install.lst ] && xargs rm < s_u_install.lst &> /dev/null && rm s_u_install.lst
    if ! [ -r s_u_vars.lst ] ;then
	echo "cannot find s_u_vars.lst"
	exit
    fi	
    {
	read S_INSTALL_DIST
	read S_BASH_RC
    } < s_u_vars.lst
    begin=$(grep -n '^##\^\^' ${S_BASH_RC} |  cut -d: -f1 | head -1)
    end=$(grep -n '^##\$\$' ${S_BASH_RC} |  cut -d: -f1 | head -1)
    rmdir /tmp/_s_clipboard 2>/dev/null
    if [ "$begin" -lt "$end" ] &> /dev/null ;then
	mv ${S_BASH_RC} ${S_BASH_RC}~
	awk "NR < ${begin} || NR > ${end}" < ${S_BASH_RC}~ > ${S_BASH_RC} && rm s_u_vars.lst
    else
	echo "you may need to clear bashrc manually"
    fi
}

for ((i = 1;i <= $#;)) ;do
    case ${!i} in
	-t)
	    shift $i
	    S_INSTALL_DIST=${!i}
	    shift $i
	    ;;
	-r)
	    shift $i
	    S_BASH_RC=${!i}
	    shift $i
	    ;;
	-u)
	    shift $i
	    s_uninstall
	    exit
	    ;;
	*)
	    let 'i++'
	    ;;
    esac
done

if [ "$S_INSTALL_DIST" = "" ] ;then
    if [ "$(id -u)" = "0" ] ;then
	S_INSTALL_DIST="/usr/bin"
    else
	S_INSTALL_DIST="${HOME}/bin"
    fi
fi

#[ -d /tmp/_s_clipboard ] || mkdir -m777 /tmp/_s_clipboard

if [ "$S_BASH_RC" = "" ] ;then
    if [[ "$S_INSTALL_DIST" =~ ^${HOME} ]] ;then
	S_BASH_RC=${HOME}/.bashrc
    else
	S_BASH_RC=/etc/bash.bashrc
    fi
fi

rm *.lst &> /dev/null

echo "${S_INSTALL_DIST}" >> s_u_vars.lst
echo "${S_BASH_RC}" >> s_u_vars.lst

for file in $(find ! -regex '\./install' -and ! -name '.*' -and ! -regex '.*/\.[^/]*/.*' -and ! -regex '.*\.lst' -and ! -regex '\./README' -and ! -regex '.*~') ;do
    file=${file#./}
    if [ "$file" = "setup.sh" ] ;then
	sed -e "s:@@install_dir:${S_INSTALL_DIST}:g" < "${file}" > ${S_INSTALL_DIST}/setup.sh
	chmod 644 ${S_INSTALL_DIST}/setup.sh
	echo "${S_INSTALL_DIST}/setup.sh" >> s_u_install.lst
	continue
    fi
    if [ "$file" = "s_init.sh" ] ;then
	install -m644 ${file} ${S_INSTALL_DIST}/${file}
	echo "${S_INSTALL_DIST}/s_init.sh" >> s_u_install.lst
	continue
    fi
    install -m755 ${file} ${S_INSTALL_DIST}/${file}
    echo "${S_INSTALL_DIST}/${file}" >> s_u_install.lst
done

if [ $(tail -n1 ${S_BASH_RC} | wc -l) = 0 ] ;then
    echo >> ${S_BASH_RC}
fi
echo '##^^this part is generate automatically when installing' >> ${S_BASH_RC}
echo "[ -r ${S_INSTALL_DIST}/setup.sh ] && . ${S_INSTALL_DIST}/setup.sh" >> ${S_BASH_RC}
echo '##$$end' >> ${S_BASH_RC}