#!/bin/bash

post_install()
{
    local S_BASH_RC="$1" S_INSTALL_DIST="$2"
    if [ $(tail -n1 ${S_BASH_RC} | wc -l) = 0 ] ;then
	echo >> ${S_BASH_RC}
    fi &&
    echo '##^^this part is generate automatically when installing' >> ${S_BASH_RC} &&
    echo "[ -r ${S_INSTALL_DIST}/setup.sh ] && . ${S_INSTALL_DIST}/setup.sh" >> ${S_BASH_RC} &&
    echo '##$$end' >> ${S_BASH_RC} || exit 1    
}

prefix=""

for ((i = 1;i <= $#;i++)) ;do
    case ${!i} in
	-t|--to)
	    let 'i++'
	    S_INSTALL_DIST=${!i}
	    ;;
	-r|--rc)
	    let 'i++'
	    S_BASH_RC=${!i}
	    ;;
	-p|--prefix)
	    let 'i++'
	    prefix=${!i}
	    ;;
	-i|--install-script)
	    
	    ;;
	*)
	    args[${#args[@]}]="${!i}"
	    ;;
    esac
done

if [ "$(id -u)" = "0" ] ;then
    S_INSTALL_DIST=${S_INSTALL_DIST:-"/usr/bin"}
    S_BASH_RC=${S_BASH_RC:-"/etc/bash.bashrc"}
else
    S_INSTALL_DIST=${S_INSTALL_DIST:-"${HOME}/bin"}
    S_BASH_RC=${S_BASH_RC:-~/.bashrc}
fi

if [[ $(id -u) == 0 ]] ;then
    s_util_dir=/usr/share/sutil
else
    s_util_dir=~/.sutil
fi

[ -d "${s_util_dir}" ] || mkdir -p "${s_util_dir}" || exit 1

s_util_dir="${prefix}/${s_util_dir}"
S_INSTALL_DIST="${prefix}/${S_INSTALL_DIST}"
S_BASH_RC="${prefix}/${S_BAHS_RC}"

filelst=${s_util_dir}/files.lst
varlst=${s_util_dir}/vars.lst
cmdlst=${s_util_dir}/cmds.lst

[ -d "${S_INSTALL_DIST}" ] || mkdir -p "${S_INSTALL_DIST}" || exit 1

cat > "${varlst}" <<EOF
${S_INSTALL_DIST}
${S_BASH_RC}
EOF

s_srcdir="$(dirname "${BASH_SOURCE}")"

ignore=("'\./install'" "'.*/\..*'" "'.*\.lst'" "'\./README'" "'.*~'" "'\./tmp'")
notcmd=('\.sh$')

currentdir="$PWD"

cd "${s_srcdir}" || exit 1

cat /dev/null | tee "${filelst}" | tee "${cmdlst}"

for file in $(for ((i = 0;i < ${#ignore[@]};i++)) ;do ((i == 0)) || echo '-and'; echo '! -regex'; echo "${ignore[i]}";done | xargs find -type f) ;do
    if [[ $file =~ $notcmd ]] ;then
	install -m644 ${file} ${S_INSTALL_DIST}/${file} &&
	echo "${S_INSTALL_DIST}/${file}" >> "${filelst}" &&
	if [[ $file == ./setup.sh ]] ;then
	    sed -e "s:@@install_dir:${S_INSTALL_DIST}:g" -i "${S_INSTALL_DIST}/${file}"
	fi || exit 1
	continue
    fi
    install -m755 ${file} ${S_INSTALL_DIST}/${file} &&
    echo "${S_INSTALL_DIST}/${file}" >> "${filelst}" &&
    basename "${file}" >> ${cmdlst} || exit 1
done

post_install "${S_BASH_RC}" "${S_INSTALL_DIST}"