#!/bin/bash
s_shelp()
{
    cat<<EOF
This command list the favorate commands names.
USAGE:
	$(basename $0) [OPTIONS] [command]
OPTIONS:
	-v/--version: show the version number and exit
	-h/--help: show this help and exit
	
EOF
}

. s_init.sh

rd_fl_t_ary()
{
    local __file="$1"
    local __array="$2"
    local IFS=$'\n'
    eval "${__array}"'=("${'"${__array}"'[@]}" $(cat '"${__file}"'))'
}

del_frm_ary()
{
    local __key="$1"
    local __array="$2"
    local __tmp_array
    eval __tmp_array'=("${'"${__array}"'[@]}")'
    local __n=${#__tmp_array[@]}
    local i
    for ((i = 0;i < __n;i++)) ;do
	[[ ${__key} == ${__tmp_array[i]} ]] && unset __tmp_array[i]
    done
    eval "${__array}"'=("${__tmp_array[@]}")'
}

apnd_to_ary()
{
    local __key="$1"
    local __array="$2"
    eval "${__array}"'=("${'"${__array}"'[@]}" '"${__key}"')'
}

cmn_cmd_lst=/usr/share/sutil/cmds.lst
spc_cmd_lst=~/.sutil/cmds.lst
usr_cmd_lst=~/.sutil/bkmrk.lst

[ -f "${usr_cmd_lst}" ] || touch "${usr_cmd_lst}" || exit 1

for ((i = 0;i < ${#args[@]};)) ;do
    case "${args[i]}" in
	-a|--add)
	    darg $i
	    [[ ${args[i]} =~ ^! ]] && {
		echo "command cannot start with !"
		exit 1
	    }
	    if [ $(tail -n1 ${usr_cmd_lst} | wc -l) = 0 ] ;then
		echo >> ${usr_cmd_lst}
	    fi &&
	    echo "${args[i]}" >> ${usr_cmd_lst} || exit 1
	    exit 0
	    ;;
	-d|--delete)
	    darg $i
	    [[ ${args[i]} =~ ^! ]] && {
		echo "command cannot start with !"
		exit 1
	    }
	    if [ $(tail -n1 ${usr_cmd_lst} | wc -l) = 0 ] ;then
		echo >> ${usr_cmd_lst}
	    fi &&
	    echo "!${args[i]}" >> ${usr_cmd_lst} || exit 1
	    exit 0
	    ;;
	*)
	    let 'i++'
	    ;;
    esac
done

cmdlst=()

[ -f "${cmn_cmd_lst}" ] && rd_fl_t_ary ${cmn_cmd_lst} cmdlst
[ -f "${spc_cmd_lst}" ] && rd_fl_t_ary ${spc_cmd_lst} cmdlst
[ -f "${usr_cmd_lst}" ] && rd_fl_t_ary ${usr_cmd_lst} cmdlst

favolst=()

for ((i = 0;i < ${#cmdlst[@]};i++)) ;do
    if [[ ${cmdlst[i]} =~ ^! ]] ;then
	del_frm_ary "${cmdlst[i]#!}" favolst
    else
	apnd_to_ary "${cmdlst[i]}" favolst
    fi
done

for ((i = 0;i < ${#favolst[@]};i++)) ;do
    echo "${i}: ${favolst[i]}"
done
