#!/bin/bash

. s_init.sh

approx=0

for ((i = 0;i < ${#args[@]};)) ;do
    case "${args[i]}" in
	-a|--apropos)
	    approx=1
	    darg $i
	    ;;
	*)
	    let 'i++'
	    ;;
    esac
done

if [[ $approx == 0 ]] &&
    ( ( [[ "${args[0]}" == 'n' ]] ||
	    [[ "${args[0]}" =~ ^[0-9] ]]) &&
	((${#args[@]} != 1)) ) ;then
    sektion="${args[0]}"
    darg 0
else
    sektion=0
fi
for query in "${args[@]}" ;do
    curl -s "http://manpages.debian.net/cgi-bin/man.cgi?query=${query}&sektion=${sektion}&format=ascii" | less
done
