#!/bin/bash

if [[ $1 =~ ^[^0-9 n]] && (($# == 1)) ;then
    curl -s "http://manpages.debian.net/cgi-bin/man.cgi?query=${1}&format=ascii" | less
else
    curl -s "http://manpages.debian.net/cgi-bin/man.cgi?query=${2}&sektion=${1}&format=ascii" | less
fi
