#!/bin/bash
background=0
for ((i = 1;i < $#;i++)) ;do
    case ${!i} in
	-b)
	    background=1
	    shift i
	    ;;
    esac
done
if [ $background == 1 ] ;then
    wget -c -r -np -k -L -p $1 &> $1.log &
elsen
    wget -c -r -np -k -L -p $1
fi

