#!/bin/bash
function s_shelp()
{
    echo "This command download a website recursively using wget"
}

. "${S_UTIL_INSTALL_DIR}/s_init.sh"

background=0
for ((i = 1;i < $#;i++)) ;do
    case ${!i} in
	-b)
	    background=1
	    shift $i
	    ;;
    esac
done
if [ $background == 1 ] ;then
    wget -c -r -np -k -L -p $1 &> $1.log &
else
    wget -c -r -np -k -L -p $1
fi

