#!/bin/bash
function s_shelp()
{
    echo "This command download a website recursively using wget"
    echo "USAGE:"
    echo $'\t'"$0 [OPTIONS] url"
    echo "OPTIONS:"
    echo $'\t'"-b/--background: run in the background"
    echo $'\t'"-v/--version: show the version number and exit"
    echo $'\t'"-h/--help: show this help and exit"
}

. s_init.sh

background=0
for ((i = 1;i < $#;)) ;do
    case ${!i} in
	-b|--background)
	    background=1
	    shift $i
	    ;;
	*)
	    let 'i++'
	    ;;
    esac
done
if [ $background == 1 ] ;then
    wget -c -r -np -k -L -p $1 &> $1.log &
else
    wget -c -r -np -k -L -p $1
fi

