#!/bin/bash
function s_shelp()
{
    echo "This command search for files in the PATH"
    echo "USAGE:"
    echo $'\t'"$0 [OPTIONS] [KEYWORDS]"
    echo "OPTIONS:"
    echo $'\t'"-r/--reg: use regular expression"
    echo $'\t'"-n/--noexec: also search not executable files"
    echo $'\t'"-p/--path PATH: search PATH instead of default PATH"
    echo $'\t'"-f/--full: show the full path of the command found"
    echo $'\t'"-v/--version: show the version number and exit"
    echo $'\t'"-h/--help: show this help and exit"
}

. "${S_UTIL_INSTALL_DIR}/s_init.sh"

NONE_EXEC=0
REG=0
FULL_PATH=0

for ((i = 0;i <= $#;)) ;do
    case ${!i} in
	-r|--reg)
	    shift $i
	    REG=1
	    ;;
	-n|--noexec)
	    shift $i
	    NONE_EXEC=1
	    ;;
	-p|--path)
	    shift $i
	    PATH=${!i}
	    shift $i
	    ;;
	-f|--full)
	    shift $i
	    FULL_PATH=1
	    ;;
	*)
	    let 'i++'
	    ;;
    esac
done

command="find -L ${PATH//:/ } -maxdepth 1 -type f"
[ ${NONE_EXEC} = 0 ] && command="${command} -and -perm /111"

if [ "$FULL_PATH" = 1 ] ;then
    EXTRA=''
else
    EXTRA='s:^.*/::g'
fi

if [ $# = "0" ] ;then
    $command | sed -e "${EXTRA}"
    exit
fi

ONE_KEYWORD=0

if [ $# = "1" ] ;then
    ONE_KEYWORD=1
fi

for ((i = 1;i <= $#;i++)) ;do
    key="${!i}"
    [ ${ONE_KEYWORD} = 0 ] && echo "${key}:"
    if [ "$REG" = 1 ] ;then
	${command} -regex ".*/${key}"
    else
	${command} -name "${key}"
    fi | sed -e "${EXTRA}"
done
