#!/bin/bash

# tool to quickly convert a latex string into pdf

echo "\\documentclass{article}\\pagestyle{empty}\\usepackage{feyn}\\begin{document}\\[" > tmp$$.tex

if [ $# == 1 ]; then
    echo $1 >> tmp$$.tex
else
    cat >> tmp$$.tex
fi


echo "\\]\\end{document}" >> tmp$$.tex

pdflatex tmp$$.tex && rm tmp$$.{tex,aux,log}
#,synctex.gz}

if [ $(uname) == "Darwin" ]; then #mac os x
    open tmp$$.pdf
else
    xopen tmp$$.pdf
fi
