#!/bin/bash

# Copyright 2010, 2011 Yu Yichao, Rudy
# yyc1992@gmail.com
# rudyht@gmail.com
#
# This file is part of s-util.
#
# s-util is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# s-util is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with s-util.  If not, see <http://www.gnu.org/licenses/>.
#

HELP_INFO='tool to quickly convert a latex string into pdf'

. s_init.sh

{
    echo '\documentclass{article}\pagestyle{empty}\usepackage{feyn}\begin{document}\['

    if [ ${#args[@]} == 1 ]; then
        echo "${args[0]}"
    else
        cat
    fi

    echo '\]\end{document}'
} > tmp$$.tex

#do you really need a && here, I think it is ok to delete those files even if pdflatex fails
pdflatex tmp$$.tex
rm tmp$$.{tex,aux,log}
#,synctex.gz}

xopen tmp$$.pdf
