#!/bin/bash

# Copyright 2010, 2011 Yu Yichao, Rudy
# yyc1992@gmail.com
# rudyht@gmail.com
#
# This file is part of s-util.
#
# s-util is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# s-util is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with s-util.  If not, see <http://www.gnu.org/licenses/>.
#

s_shelp()
{
    cat <<EOF
This command delete or show the blank at the end of every line of input files.
USAGE:
        $(basename $0) [OPTION] files
OPTIONS:
        -s/--show: only show the lines, not change anything
        -v/--version: display version and exit
        -h/--help: show this help and exit
EOF
}

. s_init.sh

change=1

for ((i = 0;i < ${#args[@]};)) ;do
    case "${args[i]}" in
        -s|--show)
            darg $i
            change=0
            ;;
        *)
            let 'i++'
            ;;
    esac
done

[[ ${#args[@]} == 0 ]] && exit 1

if [[ ${change} == 0 ]] ;then
    grep -n '[[:blank:]'$'\r''][[:blank:]'$'\r'']*$' "${args[@]}"
else
    for ((i = 0;i < ${#args[@]};i++)) ;do
        sed -i "${args[i]}" -e '/[[:blank:]\r]$/s/[[:blank:]\r]*$//g'
    done
fi
