#!/bin/bash

# Copyright 2010, 2011 Yu Yichao, Rudy
# yyc1992@gmail.com
# rudyht@gmail.com
#
# This file is part of s-util.
#
# s-util is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# s-util is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with s-util.  If not, see <http://www.gnu.org/licenses/>.
#

#TODO: backend/options

s_shelp()
{
    cat<<EOF
This command download a website recursively using wget
USAGE:
        $(basename $0) [OPTIONS] url
OPTIONS:
        -b/--background: run in the background
        -v/--version: show the version number and exit
        -h/--help: show this help and exit
EOF
}

. s_init.sh

background=0
for ((i = 0;i < ${#args[@]};)) ;do
    case "${args[i]}" in
        -b|--background)
            background=1
            darg $i
            ;;
        *)
            let 'i++'
            ;;
    esac
done
if [ $background == 1 ] ;then
    wget -c -r -np -k -L -p "${args[0]}" &> "$(echo ${args[0]} | tr '/' '_')".log &
else
    wget -c -r -np -k -L -p "${args[0]}"
fi
