#!/bin/bash

# Copyright 2010, 2011 Yu Yichao, Rudy
# yyc1992@gmail.com
# rudyht@gmail.com
#
# This file is part of s-util.
#
# s-util is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# s-util is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with s-util.  If not, see <http://www.gnu.org/licenses/>.
#

HELP_INFO='This command use xdg-open(on Linux)/open(on Mac) to open arbitrary file with default program and redirect all annoy console output to /dev/null'

. s_init.sh

[[ ${#args[@]} == 0 ]] && args[0]=.

if type xdg-open &> /dev/null; then
    if [[ -z $DISPLAY ]]; then
        exec xdg-open "${args[@]}"
    else
        exec xdg-open "${args[@]}" </dev/null &>/dev/null &
    fi
elif type open &> /dev/null; then
    exec open "${args[@]}" < /dev/null &>/dev/null &
else
    echo "Cannot find right program to use."
fi
